- name: Installer zookeeper sur Ubuntu
  apt:
    name:
      - mapr-zookeeper
    state: present
  when: "inventory_hostname in groups['ZooKeeper_nodes']"

- name: Installer cldb sur les noeuds CLDB_nodes
  apt:
    name:
      - mapr-cldb
    state: present
  when: "inventory_hostname in groups['CLDB_nodes']"

- name: Installer resource manager sur les noeuds ResourceManager_nodes
  apt:
    name:
      - mapr-resourcemanager
    state: present
  when: "inventory_hostname in groups['ResourceManager_nodes']"

- name: Installer fileserver sur les noeuds FileServer_nodes
  apt:
    name:
      - mapr-fileserver
    state: present
  when: "inventory_hostname in groups['FileServer_nodes']"

- name: Installer nfs sur les noeuds NFS_nodes
  apt:
    name:
      - mapr-nfs
    state: present
  when: "inventory_hostname in groups['NFS_nodes']"

- name: Installer nodemanager sur les noeuds NodeManager_nodes
  apt:
    name:
      - mapr-nodemanager
    state: present
  when: "inventory_hostname in groups['NodeManager_nodes']"

- name: Installer historyserver sur les noeuds HistoryServer_nodes
  apt:
    name:
      - mapr-historyserver
    state: present
  when: "inventory_hostname in groups['HistoryServer_nodes']"


- name: Installer webserver sur les noeuds WebServer_nodes
  apt:
    name:
      - mapr-webserver
    state: present
  when: "inventory_hostname in groups['WebServer_nodes']"

- name: Installer api server sur les noeuds ApiServer_nodes
  apt:
    name:
      - mapr-apiserver
    state: present
  when: "inventory_hostname in groups['ApiServer_nodes']"

- name: Installer drill sur les noeuds Drill_nodes
  apt:
    name:
      - mapr-drill
    state: present
  when: "inventory_hostname in groups['Drill_nodes']"

- name: Installer hive sur les noeuds Hive_nodes
  apt:
    name:
      - mapr-hive
      - mapr-hivemetastore
      - mapr-hiveserver2
    state: present
  when: "inventory_hostname in groups['Hive_nodes']"

- name: Installer gateway sur les noeuds Gateway_nodes
  apt:
    name:
      - mapr-gateway
    state: present
  when: "inventory_hostname in groups['Gateway_nodes']"
